-- Seed editorial Stellar Gaming 2026: exatamente 81 slides
DELETE FROM slideVersions;
DELETE FROM sourceSlides;
DELETE FROM editorialTexts;
DELETE FROM slides;
DELETE FROM reportSections;
INSERT INTO reportSections (id, code, name, description, orderIndex) VALUES
(1, 'A', 'Abertura', 'Capa, sumário e nota metodológica', 1),
(2, 'B1', 'Marco Regulatório', 'Evolução legal e mecanismos regulatórios', 2),
(3, 'B2', 'Mercado e Arrecadação', 'GGR, arrecadação, projeções e estrutura competitiva', 3),
(4, 'B3', 'Pagamentos e Enforcement', 'PIX, KYC, cadeia B2B e combate ao ilegal', 4),
(5, 'B4', 'Usuários e Jogo Responsável', 'Perfil, comportamento e proteção do apostador', 5),
(6, 'B5', 'Mídia e Patrocínios', 'Publicidade, futebol, influenciadores e transmissão', 6),
(7, 'B6', 'Competição e Consolidação', 'Concentração, M&A e sustentabilidade competitiva', 7),
(8, 'B7', 'Perspectivas 2026–2028', 'Agenda regulatória, projeções e variáveis de monitoramento', 8),
(9, 'B8', 'Contexto Global', 'Comparativos internacionais e tendências globais', 9),
(10, 'B9', 'Stellar Gaming', 'Posicionamento, metodologia e conclusão institucional', 10);

INSERT INTO slides (sectionId, deckCode, orderIndex, title, content, notes, kpiMain, bullets, sourceFooter, status, lastEditedBy) VALUES
(1, 'A1', 1, 'Brasil: Um Mercado que Nasceu para Liderar', '1. Primeiro relatório completo do mercado regulado com dados do 1º semestre 2026
2. Cobertura de 9 blocos temáticos com mais de 30 fontes primárias e oficiais
3. Dados via LAI, SPA/MF, Receita Federal, Serasa, iGaming Brazil e BNLData', NULL, 'Relatório Setorial 2026', CAST('["Primeiro relatório completo do mercado regulado com dados do 1º semestre 2026","Cobertura de 9 blocos temáticos com mais de 30 fontes primárias e oficiais","Dados via LAI, SPA/MF, Receita Federal, Serasa, iGaming Brazil e BNLData"]' AS JSON), 'Stellar Gaming · Born to Lead · Agosto 2026', 'approved', NULL),
(1, 'A2', 2, 'Sumário Executivo', '1. Bloco 1: Marco Regulatório — Bloco 2: Mercado e Arrecadação
2. Blocos 3–4: Pagamentos, Enforcement, Perfil do Usuário e Jogo Responsável
3. Blocos 5–9: Mídia, Competição, Perspectivas, Contexto Global e Stellar Gaming', NULL, '9 Blocos · 81 Slides · +30 Fontes', CAST('["Bloco 1: Marco Regulatório — Bloco 2: Mercado e Arrecadação","Blocos 3–4: Pagamentos, Enforcement, Perfil do Usuário e Jogo Responsável","Blocos 5–9: Mídia, Competição, Perspectivas, Contexto Global e Stellar Gaming"]' AS JSON), 'Stellar Gaming · Relatório Setorial 2026', 'approved', NULL),
(1, 'A3', 3, 'Nota Metodológica', '1. Dados ATUAL (2026): base principal do relatório — sempre identificados
2. Dados REF (pré-2026): uso comparativo e histórico — sempre sinalizados
3. Fontes primárias preferidas: LAI, SPA/MF, Receita Federal, Serasa Experian', NULL, 'Transparência como princípio', CAST('["Dados ATUAL (2026): base principal do relatório — sempre identificados","Dados REF (pré-2026): uso comparativo e histórico — sempre sinalizados","Fontes primárias preferidas: LAI, SPA/MF, Receita Federal, Serasa Experian"]' AS JSON), 'Metodologia Stellar Gaming 2026', 'approved', NULL),
(2, 'B1.1', 4, 'Da Proibição à Regulação: 8 Anos de Transformação', '1. 2018: Lei 13.756 autoriza apostas de quota fixa no Brasil
2. 2023: Lei 14.790 estabelece o modelo regulatório definitivo
3. Jan/2025: 79 operadoras autorizadas iniciam operações — mercado regulado começa', NULL, 'Jan/2025 → Mercado regulado ativo', CAST('["2018: Lei 13.756 autoriza apostas de quota fixa no Brasil","2023: Lei 14.790 estabelece o modelo regulatório definitivo","Jan/2025: 79 operadoras autorizadas iniciam operações — mercado regulado começa"]' AS JSON), 'Fonte: MF/SPA; Lei 14.790/2023; Lei 13.756/2018', 'approved', NULL),
(2, 'B1.2', 5, 'Lei 14.790/2023: Os Quatro Pilares da Regulação', '1. Licenciamento obrigatório via SPA/MF — outorga de R$ 30 mi por 5 anos
2. Tributação sobre GGR: 12% (2025) → 13% (2026) → 14% (2027) → 15% (2028)
3. Jogo responsável e proteção ao consumidor como obrigações legais dos operadores', NULL, '4 pilares estruturantes', CAST('["Licenciamento obrigatório via SPA/MF — outorga de R$ 30 mi por 5 anos","Tributação sobre GGR: 12% (2025) → 13% (2026) → 14% (2027) → 15% (2028)","Jogo responsável e proteção ao consumidor como obrigações legais dos operadores"]' AS JSON), 'Fonte: Lei 14.790/2023; LC 224/2025', 'approved', NULL),
(2, 'B1.3', 6, '1º Ano Regulado: Balanço Oficial SPA/MF', '1. 25,2 milhões de CPFs cadastrados em plataformas autorizadas em 2025
2. R$ 9,95 bilhões em tributos federais recolhidos — acima das projeções iniciais
3. 25 mil+ sites ilegais bloqueados em parceria com Anatel no primeiro ano', NULL, 'R$ 37 bi GGR em 2025', CAST('["25,2 milhões de CPFs cadastrados em plataformas autorizadas em 2025","R$ 9,95 bilhões em tributos federais recolhidos — acima das projeções iniciais","25 mil+ sites ilegais bloqueados em parceria com Anatel no primeiro ano"]' AS JSON), 'Fonte: SPA/MF — Balanço 1º Ano Regulado, jan/2026', 'approved', NULL),
(2, 'B1.4', 7, 'Decreto 13.033/2026: O Cerco Financeiro ao Ilegal', '1. Publicado em 18/06/2026 — primeiro mecanismo de bloqueio administrativo de contas
2. Encerra indefinição histórica: SPA assume responsabilidade sobre fintechs parceiras de ilegais
3. Receita bloqueada vai para o Fundo Nacional de Segurança Pública', NULL, 'R$ 50 bi bloqueados', CAST('["Publicado em 18/06/2026 — primeiro mecanismo de bloqueio administrativo de contas","Encerra indefinição histórica: SPA assume responsabilidade sobre fintechs parceiras de ilegais","Receita bloqueada vai para o Fundo Nacional de Segurança Pública"]' AS JSON), 'Fonte: Decreto nº 13.033/2026; BNLData, jun/2026', 'approved', NULL),
(2, 'B1.5', 8, 'Portaria 1.766/2026: Responsabilidade Tributária Solidária', '1. IFs e fintechs têm 24 horas para bloquear contas após notificação formal da SPA
2. Influenciadores que divulgam bets ilegais respondem por IR, PIS e Cofins da atividade
3. Primeira norma que alcança toda a cadeia financeira e de comunicação do ilegal', NULL, '24h para cumprir ou responder', CAST('["IFs e fintechs têm 24 horas para bloquear contas após notificação formal da SPA","Influenciadores que divulgam bets ilegais respondem por IR, PIS e Cofins da atividade","Primeira norma que alcança toda a cadeia financeira e de comunicação do ilegal"]' AS JSON), 'Fonte: Portaria MF nº 1.766/2026, 17/06/2026', 'approved', NULL),
(2, 'B1.6', 9, 'Prediction Markets: Brasil Entre os Primeiros a Regular', '1. Mercados de previsão (Polymarket, Kalshi) equiparados a bets para fins regulatórios
2. Contratos derivativos sobre eventos políticos, esportivos e de entretenimento proibidos
3. Brasil se posiciona na vanguarda global — decisão antes de EUA e Europa fecharem o debate', NULL, 'Resolução CMN 5.298/2026', CAST('["Mercados de previsão (Polymarket, Kalshi) equiparados a bets para fins regulatórios","Contratos derivativos sobre eventos políticos, esportivos e de entretenimento proibidos","Brasil se posiciona na vanguarda global — decisão antes de EUA e Europa fecharem o debate"]' AS JSON), 'Fonte: Resolução CMN 5.298/2026; Nota Técnica SPA 2958/2026', 'approved', NULL),
(2, 'B1.7', 10, 'Portaria 1.231/2024: O Marco do Jogo Responsável', '1. Autolimitação de apostas e depósitos é obrigação — não opcional
2. Operadores devem enviar alertas regulares sobre tempo de jogo e valor apostado
3. Apostador tem direito de encerrar conta e resgatar saldo integral sem custo', NULL, 'Obrigações legais para todos os operadores', CAST('["Autolimitação de apostas e depósitos é obrigação — não opcional","Operadores devem enviar alertas regulares sobre tempo de jogo e valor apostado","Apostador tem direito de encerrar conta e resgatar saldo integral sem custo"]' AS JSON), 'Fonte: Portaria SPA/MF nº 1.231/2024', 'approved', NULL),
(2, 'B1.8', 11, 'Combate ao Ilegal: A Evolução do Placar', '1. Jan/2026: 25 mil sites · Abr/2026: 39 mil · Jun/2026: mais de 50 mil plataformas bloqueadas
2. 697 contas bancárias encerradas · 172 processos instaurados contra operadores
3. 412 processos contra influenciadores — 324 perfis e 229 publicações removidos', NULL, '50.000+ plataformas derrubadas', CAST('["Jan/2026: 25 mil sites · Abr/2026: 39 mil · Jun/2026: mais de 50 mil plataformas bloqueadas","697 contas bancárias encerradas · 172 processos instaurados contra operadores","412 processos contra influenciadores — 324 perfis e 229 publicações removidos"]' AS JSON), 'Fonte: SPA/MF, jan/abr/jun 2026', 'approved', NULL),
(2, 'B1.9', 12, 'Desenrola Adimplentes: Crédito + Autoexclusão', '1. Lançado 29/06/2026: refinanciamento a 1,99% a.m. para trabalhadores informais
2. Condição: bloqueio de CPF em todas as bets por mínimo de 6 meses
3. Primeiro programa de crédito popular a usar autoexclusão de apostas como contrapartida', NULL, '800 mil fora das bets como contrapartida', CAST('["Lançado 29/06/2026: refinanciamento a 1,99% a.m. para trabalhadores informais","Condição: bloqueio de CPF em todas as bets por mínimo de 6 meses","Primeiro programa de crédito popular a usar autoexclusão de apostas como contrapartida"]' AS JSON), 'Fonte: MF/SPA; BNLData, jun/2026', 'approved', NULL),
(2, 'B1.10', 13, 'ECA Digital: Proteção de Menores nas Plataformas', '1. Mar/2026: operadoras obrigadas a verificar maioridade com dados biométricos e documentais
2. Menores de 18 anos proibidos de criar contas, depositar ou realizar qualquer aposta
3. Responsabilidade dos operadores estendida às plataformas de pagamento integradas', NULL, 'Verificação de idade obrigatória', CAST('["Mar/2026: operadoras obrigadas a verificar maioridade com dados biométricos e documentais","Menores de 18 anos proibidos de criar contas, depositar ou realizar qualquer aposta","Responsabilidade dos operadores estendida às plataformas de pagamento integradas"]' AS JSON), 'Fonte: ECA Digital, mar/2026; SPA/MF', 'approved', NULL),
(3, 'B2.1', 14, 'GGR do 1º Semestre 2026: R$ 20,07 Bilhões', '1. +15,3% sobre o 1S/2025 (R$ 17,4 bi) — crescimento consistente, não explosão
2. Dados via Lei de Acesso à Informação junto à SPA/MF — fonte primária oficial
3. 87 operadoras autorizadas e 188 marcas ativas — crescimento de 11,5% de operadoras', NULL, 'R$ 20,07 bi (+15,3%)', CAST('["+15,3% sobre o 1S/2025 (R$ 17,4 bi) — crescimento consistente, não explosão","Dados via Lei de Acesso à Informação junto à SPA/MF — fonte primária oficial","87 operadoras autorizadas e 188 marcas ativas — crescimento de 11,5% de operadoras"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(3, 'B2.2', 15, 'Evolução Mensal: A Copa Não Foi o Pico', '1. Jan: R$ 4,29 bi · Fev-Mar: R$ 2,8 bi · Abr-Mai: recuperação · Jun (Copa): R$ 3,34 bi
2. Junho teve 19 dias de Copa do Mundo e 72 partidas — foi o menor GGR do semestre
3. Pico em janeiro explica-se pela antecipação dos calendários esportivos ao início do ano', NULL, 'Janeiro: R$ 4,29 bi (pico real)', CAST('["Jan: R$ 4,29 bi · Fev-Mar: R$ 2,8 bi · Abr-Mai: recuperação · Jun (Copa): R$ 3,34 bi","Junho teve 19 dias de Copa do Mundo e 72 partidas — foi o menor GGR do semestre","Pico em janeiro explica-se pela antecipação dos calendários esportivos ao início do ano"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(3, 'B2.3', 16, 'Turnover de R$ 410,85 bi e RTP de 92,2%', '1. R$ 410,85 bilhões apostados · R$ 377,86 bi devolvidos em prêmios no 1S/2026
2. Taxa de Retorno ao Apostador (RTP) de 92,2% — compatível com padrões internacionais maduros
3. Margem efetiva do setor: 4,9% do turnover — não os 15-20% que parte da narrativa sugere', NULL, 'R$ 4,90 retidos de cada R$ 100 apostados', CAST('["R$ 410,85 bilhões apostados · R$ 377,86 bi devolvidos em prêmios no 1S/2026","Taxa de Retorno ao Apostador (RTP) de 92,2% — compatível com padrões internacionais maduros","Margem efetiva do setor: 4,9% do turnover — não os 15-20% que parte da narrativa sugere"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(3, 'B2.4', 17, 'Arrecadação Tributária RFB: Série Completa 2026', '1. Jan: R$ 368 mi → Jun: R$ 513 mi — crescimento de 39,3% na arrecadação de quota fixa
2. R$ 2,48 bi de apostas de quota fixa · R$ 4,96 bi de loterias no 1S/2026
3. Acumulado jan-mai/2026: R$ 5,89 bi (+85,88% vs jan-mai/2025 — R$ 3,17 bi)', NULL, 'R$ 7,44 bi em 6 meses', CAST('["Jan: R$ 368 mi → Jun: R$ 513 mi — crescimento de 39,3% na arrecadação de quota fixa","R$ 2,48 bi de apostas de quota fixa · R$ 4,96 bi de loterias no 1S/2026","Acumulado jan-mai/2026: R$ 5,89 bi (+85,88% vs jan-mai/2025 — R$ 3,17 bi)"]' AS JSON), 'Fonte: Receita Federal do Brasil; BNLData, mai-ago/2026', 'approved', NULL),
(3, 'B2.5', 18, 'Convergência Fiscal: O Achado Metodológico', '1. RFB arrecadou R$ 2.483.210.886,95 em apostas de quota fixa no 1S/2026
2. SPA/MF calculou R$ 2.488.647.762,68 em destinações sociais no mesmo período
3. Os dois valores NÃO devem ser somados — capturam o mesmo fluxo: 12% do GGR por lei', NULL, 'Diferença de apenas 0,2%', CAST('["RFB arrecadou R$ 2.483.210.886,95 em apostas de quota fixa no 1S/2026","SPA/MF calculou R$ 2.488.647.762,68 em destinações sociais no mesmo período","Os dois valores NÃO devem ser somados — capturam o mesmo fluxo: 12% do GGR por lei"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI; RFB, ago/2026', 'approved', NULL),
(3, 'B2.6', 19, 'Escala de Alíquotas: 2025 a 2028', '1. 2025: 12% sobre GGR · 2026: 13% · 2027: 14% · 2028: 15% (LC 224/2025)
2. Crescimento estrutural de receita independente da expansão do mercado
3. Impacto estimado só pelo aumento de alíquota em 2026: +R$ 850 mi (MF)', NULL, 'De 12% para 15% até 2028', CAST('["2025: 12% sobre GGR · 2026: 13% · 2027: 14% · 2028: 15% (LC 224/2025)","Crescimento estrutural de receita independente da expansão do mercado","Impacto estimado só pelo aumento de alíquota em 2026: +R$ 850 mi (MF)"]' AS JSON), 'Fonte: Lei Complementar 224/2025', 'approved', NULL),
(3, 'B2.7', 20, 'Destinação Social: R$ 2,49 bi em 6 Meses', '1. Esporte: R$ 870 mi · Turismo: R$ 641 mi · Segurança Pública: R$ 310 mi
2. Educação: R$ 228 mi · Seguridade Social: R$ 228 mi · Saúde: R$ 24 mi
3. SUS oferece até 100 mil teleatendimentos/mês para dependência em jogos', NULL, '12,4% do GGR para políticas públicas', CAST('["Esporte: R$ 870 mi · Turismo: R$ 641 mi · Segurança Pública: R$ 310 mi","Educação: R$ 228 mi · Seguridade Social: R$ 228 mi · Saúde: R$ 24 mi","SUS oferece até 100 mil teleatendimentos/mês para dependência em jogos"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(3, 'B2.8', 21, 'Gasto Médio por Apostador: R$ 108,27/mês', '1. Alta de 5,0% sobre o mesmo período de 2025 (R$ 103,10/mês)
2. Crescimento do gasto médio acompanhou em ritmo próximo o crescimento do GGR
3. Indica maturação do comportamento do apostador — não explosão de novos usuários', NULL, 'R$ 108,27/mês (+5%)', CAST('["Alta de 5,0% sobre o mesmo período de 2025 (R$ 103,10/mês)","Crescimento do gasto médio acompanhou em ritmo próximo o crescimento do GGR","Indica maturação do comportamento do apostador — não explosão de novos usuários"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(3, 'B2.9', 22, 'Comparativo 1S/2025 vs 1S/2026', '1. GGR: R$ 17,4 bi (1S25) → R$ 20,07 bi (1S26) · Operadoras: 78 → 87
2. Crescimento de base de apostadores: +2.767.762 CPFs únicos (+9,84%)
3. Crescimento moderado de dois dígitos baixos — mercado em maturação, não em boom', NULL, '+15,3% GGR · +9,84% apostadores', CAST('["GGR: R$ 17,4 bi (1S25) → R$ 20,07 bi (1S26) · Operadoras: 78 → 87","Crescimento de base de apostadores: +2.767.762 CPFs únicos (+9,84%)","Crescimento moderado de dois dígitos baixos — mercado em maturação, não em boom"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(3, 'B2.10', 23, 'Market Share por Operadora: Top 10', '1. Bet365 lidera com ~17,2% do GGR · Betano (~14,8%) · Sporting (~12,3%)
2. Top 3 concentram 44,3% do GGR total do semestre
3. 187 marcas no mercado — 90% do volume concentrado em menos de 20 marcas', NULL, '10 operadoras = 67% do mercado', CAST('["Bet365 lidera com ~17,2% do GGR · Betano (~14,8%) · Sporting (~12,3%)","Top 3 concentram 44,3% do GGR total do semestre","187 marcas no mercado — 90% do volume concentrado em menos de 20 marcas"]' AS JSON), 'Fonte: BNLData; iGaming Brazil, jul/2026', 'approved', NULL),
(3, 'B2.11', 24, 'Os 5 Milhões Fora das Plataformas', '1. 3 mi: beneficiários Bolsa Família/BPC proibidos por lei de acessar plataformas
2. 1,2 mi: autoexclusão voluntária ativa · 800 mil: programa Desenrola
3. Restrições regulatórias ativas explicam parte do crescimento moderado do GGR', NULL, '5 milhões impedidos de apostar', CAST('["3 mi: beneficiários Bolsa Família/BPC proibidos por lei de acessar plataformas","1,2 mi: autoexclusão voluntária ativa · 800 mil: programa Desenrola","Restrições regulatórias ativas explicam parte do crescimento moderado do GGR"]' AS JSON), 'Fonte: Ministro Dario Durigan, 13/08/2026', 'approved', NULL),
(3, 'B2.12', 25, 'GGR 2025: O Ano de Abertura', '1. 2025 foi o primeiro ano completo do mercado regulado de quota fixa no Brasil
2. 1S/2025: R$ 17,4 bi · 2S/2025 estimado R$ 19,6 bi · Total: ~R$ 37 bi
3. Base comparativa para os próximos anos — mercado ainda em fase de calibragem', NULL, 'R$ 37 bi — 1º ano regulado', CAST('["2025 foi o primeiro ano completo do mercado regulado de quota fixa no Brasil","1S/2025: R$ 17,4 bi · 2S/2025 estimado R$ 19,6 bi · Total: ~R$ 37 bi","Base comparativa para os próximos anos — mercado ainda em fase de calibragem"]' AS JSON), 'Fonte: SPA/MF; IBJR; BNLData jan/2026', 'approved', NULL),
(3, 'B2.13', 26, 'Projeção GGR 2026: Cenário Base', '1. Média mensal do 1S/2026: R$ 3,35 bi · Se mantida: R$ 40 bi no ano
2. Fatores de aceleração: +1 p.p. na alíquota, mais operadoras, Copa no 2S
3. Fatores de moderação: 5 mi bloqueados, restrições de publicidade em debate', NULL, 'R$ 38–42 bi projetados em 2026', CAST('["Média mensal do 1S/2026: R$ 3,35 bi · Se mantida: R$ 40 bi no ano","Fatores de aceleração: +1 p.p. na alíquota, mais operadoras, Copa no 2S","Fatores de moderação: 5 mi bloqueados, restrições de publicidade em debate"]' AS JSON), 'Fonte: Projeção Stellar Gaming com base em SPA/MF via LAI, ago/2026', 'approved', NULL),
(3, 'B2.14', 27, 'Projeção GGR 2027-2028', '1. 2027: alíquota 14% sobre base crescente · projeção R$ 48–55 bi de GGR
2. 2028: alíquota 15% — patamar de maturidade · projeção R$ 55–65 bi
3. CAGR implícito de ~25–30% ao ano — em linha com mercados em fase de maturação', NULL, 'R$ 60 bi projetados para 2028', CAST('["2027: alíquota 14% sobre base crescente · projeção R$ 48–55 bi de GGR","2028: alíquota 15% — patamar de maturidade · projeção R$ 55–65 bi","CAGR implícito de ~25–30% ao ano — em linha com mercados em fase de maturação"]' AS JSON), 'Fonte: Projeção Stellar Gaming; Goldman Sachs, mar/2026', 'approved', NULL),
(3, 'B2.15', 28, 'A Narrativa da ''Explosão'' e o Que os Dados Dizem', '1. Volume apostado caiu de R$ 90 bi (jan) para R$ 56 bi (jun) — trajetória de queda contínua
2. Copa do Mundo não produziu o boom projetado — junho foi o menor GGR do semestre
3. Ausência de dados públicos é o terreno onde proliferam as narrativas mais distorcidas', NULL, '+15,3% — crescimento, não explosão', CAST('["Volume apostado caiu de R$ 90 bi (jan) para R$ 56 bi (jun) — trajetória de queda contínua","Copa do Mundo não produziu o boom projetado — junho foi o menor GGR do semestre","Ausência de dados públicos é o terreno onde proliferam as narrativas mais distorcidas"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(4, 'B3.1', 29, 'PIX: A Infraestrutura Central do Ecossistema', '1. PIX é o meio de pagamento dominante por velocidade, gratuidade e alcance nacional
2. Cartão de crédito representa apenas ~12% dos depósitos nas plataformas reguladas
3. Regulação do BCB sobre bets via PIX: monitoramento em tempo real a partir de dez/2026', NULL, 'PIX em mais de 78% dos depósitos', CAST('["PIX é o meio de pagamento dominante por velocidade, gratuidade e alcance nacional","Cartão de crédito representa apenas ~12% dos depósitos nas plataformas reguladas","Regulação do BCB sobre bets via PIX: monitoramento em tempo real a partir de dez/2026"]' AS JSON), 'Fonte: ABFintechs, abr/2026; BCB; SPA/MF', 'approved', NULL),
(4, 'B3.2', 30, 'KYC Obrigatório: Identidade Como Ferramenta Regulatória', '1. CPF, biometria e geolocalização obrigatórios em todas as plataformas autorizadas
2. KYC integrado ao SIGAP permite rastreamento e auditoria em tempo real pela SPA
3. Dados do SIGAP geraram o perfil demográfico mais preciso já produzido sobre apostadores no Brasil', NULL, '100% dos apostadores identificados', CAST('["CPF, biometria e geolocalização obrigatórios em todas as plataformas autorizadas","KYC integrado ao SIGAP permite rastreamento e auditoria em tempo real pela SPA","Dados do SIGAP geraram o perfil demográfico mais preciso já produzido sobre apostadores no Brasil"]' AS JSON), 'Fonte: SPA/MF; SIGAP; Portaria 1.231/2024', 'approved', NULL),
(4, 'B3.3', 31, 'Cadeia B2B: Os Bastidores do Mercado', '1. ~70 provedores de jogos (estúdios + agregadores) · ~34 plataformas (PAMs)
2. ~20 provedores de KYC · ~11 de odds/dados esportivos · ~7 de sportsbook
3. SPA-MF audiência pública jun/2026 para regulamentar certificação — norma final dez/2026', NULL, '~135 provedores no ecossistema', CAST('["~70 provedores de jogos (estúdios + agregadores) · ~34 plataformas (PAMs)","~20 provedores de KYC · ~11 de odds/dados esportivos · ~7 de sportsbook","SPA-MF audiência pública jun/2026 para regulamentar certificação — norma final dez/2026"]' AS JSON), 'Fonte: BNLData; SPA-MF audiência pública, jun/2026', 'approved', NULL),
(4, 'B3.4', 32, 'Operação Conto da Sorte: A Escala do Ilegal', '1. 37 empresas de um único grupo declararam R$ 400-500 mi — Receita encontrou R$ 50 bi reais
2. Uso de fintechs para lavagem e evasão: o caso mais emblemático do período regulado
3. Revelou como o mercado ilegal usa estruturas regulares como fachada financeira', NULL, 'R$ 50 bi em 10 meses via 37 empresas', CAST('["37 empresas de um único grupo declararam R$ 400-500 mi — Receita encontrou R$ 50 bi reais","Uso de fintechs para lavagem e evasão: o caso mais emblemático do período regulado","Revelou como o mercado ilegal usa estruturas regulares como fachada financeira"]' AS JSON), 'Fonte: Receita Federal; BNLData, jun/2026', 'approved', NULL),
(4, 'B3.5', 33, 'Autoexclusão: 1,2 Milhão de Pedidos Voluntários', '1. Plataforma Centralizada: 217 mil pedidos nos primeiros 40 dias (jan/2026)
2. Motivo mais frequente: ''perda de controle — saúde mental'' (37-40% dos pedidos)
3. Sistema nacional conecta TODAS as 87 operadoras — autoexclusão em uma vale para todas', NULL, '1,2 mi de autoexclusões voluntárias', CAST('["Plataforma Centralizada: 217 mil pedidos nos primeiros 40 dias (jan/2026)","Motivo mais frequente: ''perda de controle — saúde mental'' (37-40% dos pedidos)","Sistema nacional conecta TODAS as 87 operadoras — autoexclusão em uma vale para todas"]' AS JSON), 'Fonte: SPA/MF, jan/2026; Ministro Durigan, ago/2026', 'approved', NULL),
(4, 'B3.6', 34, 'Fintechs na Mira: 24h Para Agir', '1. Portaria 1.766/2026: IFs que mantiverem contas de ilegais após notificação respondem pelos tributos
2. Prazo: 24 horas após notificação formal da SPA para adotar medidas restritivas
3. Alcança pessoa física e jurídica que divulgar publicidade de operadores sem autorização', NULL, 'Responsabilidade tributária solidária', CAST('["Portaria 1.766/2026: IFs que mantiverem contas de ilegais após notificação respondem pelos tributos","Prazo: 24 horas após notificação formal da SPA para adotar medidas restritivas","Alcança pessoa física e jurídica que divulgar publicidade de operadores sem autorização"]' AS JSON), 'Fonte: Portaria MF nº 1.766/2026; BNLData, jun/2026', 'approved', NULL),
(4, 'B3.7', 35, 'Influenciadores: Do Marketing ao Risco Fiscal', '1. 412 processos abertos pela SPA · 324 perfis removidos · 229 publicações derrubadas
2. A partir de jun/2026: influenciadores de bets ilegais respondem por IR e PIS/Cofins da atividade
3. Dilema: influenciadores de marcas reguladas seguem operando — diferenciação é chave', NULL, '412 processos administrativos abertos', CAST('["412 processos abertos pela SPA · 324 perfis removidos · 229 publicações derrubadas","A partir de jun/2026: influenciadores de bets ilegais respondem por IR e PIS/Cofins da atividade","Dilema: influenciadores de marcas reguladas seguem operando — diferenciação é chave"]' AS JSON), 'Fonte: SPA/MF, jan/2026; Receita Federal, jun/2026', 'approved', NULL),
(4, 'B3.8', 36, 'Combate ao Ilegal: A Eficácia dos Mecanismos', '1. Apesar do avanço, mercado ilegal ainda representa 41-51% das plataformas ativas no Brasil
2. Impacto econômico estimado do ilegal: R$ 38,8 bi/ano (80% em danos à saúde)
3. Perfil do apostador ilegal: 69% entre 18-29 anos e 63% com renda até 2 SM', NULL, '41-51% das plataformas ainda são ilegais', CAST('["Apesar do avanço, mercado ilegal ainda representa 41-51% das plataformas ativas no Brasil","Impacto econômico estimado do ilegal: R$ 38,8 bi/ano (80% em danos à saúde)","Perfil do apostador ilegal: 69% entre 18-29 anos e 63% com renda até 2 SM"]' AS JSON), 'Fonte: MF/SPA coletiva jun/2026; BNLData', 'approved', NULL),
(5, 'B4.1', 37, '30,9 Milhões: Entendendo o Número Corretamente', '1. 30.895.934 CPFs com cadastro ativo: período acumulado de 18 meses — NÃO um semestre
2. Comparação direta com 17,7 mi do 1S/2025 é metodologicamente incorreta
3. Crescimento real: +2.767.762 CPFs únicos no 1S/2026 sobre a base de 2025 (+9,84%)', NULL, '30,9 mi CPFs — 18 meses acumulados', CAST('["30.895.934 CPFs com cadastro ativo: período acumulado de 18 meses — NÃO um semestre","Comparação direta com 17,7 mi do 1S/2025 é metodologicamente incorreta","Crescimento real: +2.767.762 CPFs únicos no 1S/2026 sobre a base de 2025 (+9,84%)"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(5, 'B4.2', 38, '15,2 Milhões Ativos no 1T26: A Distinção Crítica', '1. 15.186.243 CPFs com atividade real no 1T/2026 — dado do relatório oficial SIGAP
2. Diferença crucial: 30,9 mi registrados ≠ 15,2 mi que efetivamente apostaram
3. Base ativa é o dado relevante para análise de mercado — não os cadastros totais', NULL, '15,2 mi apostadores genuinamente ativos', CAST('["15.186.243 CPFs com atividade real no 1T/2026 — dado do relatório oficial SIGAP","Diferença crucial: 30,9 mi registrados ≠ 15,2 mi que efetivamente apostaram","Base ativa é o dado relevante para análise de mercado — não os cadastros totais"]' AS JSON), 'Fonte: iGaming Brazil / SPA-MF via SIGAP, jul/2026', 'approved', NULL),
(5, 'B4.3', 39, 'Perfil Demográfico do Apostador Brasileiro', '1. 68,47% homens e 31,53% mulheres (1S/2026) — perfil estável em relação a 2025
2. Faixa 31-40 anos: 28,95% · 25-30 anos: 21,98% · Até 24 anos: 21,30%
3. Grupos economicamente ativos (25-50 anos) respondem por 67,63% da base total', NULL, '68% homens · 31-40 anos dominam', CAST('["68,47% homens e 31,53% mulheres (1S/2026) — perfil estável em relação a 2025","Faixa 31-40 anos: 28,95% · 25-30 anos: 21,98% · Até 24 anos: 21,30%","Grupos economicamente ativos (25-50 anos) respondem por 67,63% da base total"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI; SIGAP, ago/2026', 'approved', NULL),
(5, 'B4.4', 40, 'Comportamento Multiplataforma: O Apostador Não É Fiel', '1. 55,64% dos apostadores ativos operam em duas ou mais plataformas simultaneamente
2. 17,96% usam duas · 9,89% usam três · 27,78% têm conta em quatro ou mais
3. Implicação estratégica: a batalha não é por cadastro — é por engajamento e preferência', NULL, '55,64% usam 2+ plataformas', CAST('["55,64% dos apostadores ativos operam em duas ou mais plataformas simultaneamente","17,96% usam duas · 9,89% usam três · 27,78% têm conta em quatro ou mais","Implicação estratégica: a batalha não é por cadastro — é por engajamento e preferência"]' AS JSON), 'Fonte: iGaming Brazil / SPA-MF via SIGAP, jul/2026', 'approved', NULL),
(5, 'B4.5', 41, 'Inadimplência no Brasil: O Contexto Macro', '1. 38,1% de crescimento na inadimplência entre 2016 e 2026 — Serasa Experian
2. 49,9% da população adulta está inadimplente · 70,5% da renda comprometida em média
3. Crescimento ocorreu por pandemia, juros baixos com crédito fácil e inflação — NÃO por bets', NULL, '81,7 mi inadimplentes em 2026', CAST('["38,1% de crescimento na inadimplência entre 2016 e 2026 — Serasa Experian","49,9% da população adulta está inadimplente · 70,5% da renda comprometida em média","Crescimento ocorreu por pandemia, juros baixos com crédito fácil e inflação — NÃO por bets"]' AS JSON), 'Fonte: Serasa Experian — Mapa da Inadimplência 10 Anos, fev/2026', 'approved', NULL),
(5, 'B4.6', 42, 'O Argumento Que os Dados Derrubam', '1. Mercado regulado de bets existe desde jan/2025 — inadimplência crescia desde 2022
2. Inadimplência entre jovens (18-40 anos) CAIU no período 2016-2026
3. Atribuir endividamento estrutural de uma década às bets contradiz a evidência disponível', NULL, 'Inadimplência cresceu antes das bets existirem', CAST('["Mercado regulado de bets existe desde jan/2025 — inadimplência crescia desde 2022","Inadimplência entre jovens (18-40 anos) CAIU no período 2016-2026","Atribuir endividamento estrutural de uma década às bets contradiz a evidência disponível"]' AS JSON), 'Fonte: Serasa Experian — Mapa da Inadimplência, fev/2026', 'approved', NULL),
(5, 'B4.7', 43, 'Saúde Mental: O Que a Ciência Diz (e Não Diz)', '1. The Lancet Public Health Commission (2024): evidência robusta de danos, mas sem causalidade exclusiva
2. Transtorno mental frequentemente precede o jogo — relação é bidirecional e mediada
3. A ciência NÃO afirma: ''o jogo causa depressão'' ou ''o jogo causa suicídio'' como relação exclusiva', NULL, 'Relação bidirecional — não causal exclusiva', CAST('["The Lancet Public Health Commission (2024): evidência robusta de danos, mas sem causalidade exclusiva","Transtorno mental frequentemente precede o jogo — relação é bidirecional e mediada","A ciência NÃO afirma: ''o jogo causa depressão'' ou ''o jogo causa suicídio'' como relação exclusiva"]' AS JSON), 'Fonte: The Lancet Public Health Commission on Gambling, 2024', 'approved', NULL),
(5, 'B4.8', 44, 'Comparativo de Danos: Cigarro, Álcool e Apostas', '1. Tabaco: 8,71 mi mortes globais em 2019 (GBD/The Lancet) — 2º maior risco de mortalidade
2. Álcool: ~3 mi mortes em 2016 — nível ''zero'' minimiza perda de saúde (The Lancet)
3. Apostas: danos fortíssimos em saúde mental e finanças — carga de doença ainda menor mensurada', NULL, 'Cigarro e álcool têm mais evidências de dano fatal', CAST('["Tabaco: 8,71 mi mortes globais em 2019 (GBD/The Lancet) — 2º maior risco de mortalidade","Álcool: ~3 mi mortes em 2016 — nível ''zero'' minimiza perda de saúde (The Lancet)","Apostas: danos fortíssimos em saúde mental e finanças — carga de doença ainda menor mensurada"]' AS JSON), 'Fonte: GBD 2019, The Lancet; Lancet Commission 2024', 'approved', NULL),
(5, 'B4.9', 45, 'O Gambling Disorder: A Única Exceção Científica', '1. Gambling Disorder é reconhecido como condição primária pelo DSM-5 e CID-11
2. Critérios: perda de controle, apostas crescentes, abstinência, prejuízo social e financeiro
3. Prevalência estimada: 80 mi adultos com Gambling Disorder globalmente (The Lancet 2024)', NULL, 'Reconhecido no DSM-5 e CID-11', CAST('["Gambling Disorder é reconhecido como condição primária pelo DSM-5 e CID-11","Critérios: perda de controle, apostas crescentes, abstinência, prejuízo social e financeiro","Prevalência estimada: 80 mi adultos com Gambling Disorder globalmente (The Lancet 2024)"]' AS JSON), 'Fonte: DSM-5; CID-11; The Lancet Public Health Commission, 2024', 'approved', NULL),
(5, 'B4.10', 46, 'SUS: Tratamento para Dependência em Jogos', '1. Programa do Ministério da Saúde: teleatendimento sigiloso via RAPS (Rede Psicossocial)
2. Parceria com Hospital Sírio-Libanês (Proadi-SUS) — contrato de R$ 2,9 mi
3. Financiado pelos R$ 24,19 mi destinados à Saúde pelos operadores no 1S/2026', NULL, 'Até 100 mil atendimentos/mês', CAST('["Programa do Ministério da Saúde: teleatendimento sigiloso via RAPS (Rede Psicossocial)","Parceria com Hospital Sírio-Libanês (Proadi-SUS) — contrato de R$ 2,9 mi","Financiado pelos R$ 24,19 mi destinados à Saúde pelos operadores no 1S/2026"]' AS JSON), 'Fonte: Ministério da Saúde; BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(5, 'B4.11', 47, 'Autoexclusão: A Ferramenta de Proteção em Escala', '1. Total de 5 mi fora das plataformas: 1,2 mi voluntários + 3 mi Bolsa Família + 800 mi Desenrola
2. Plataforma centralizada cobre TODAS as 87 operadoras autorizadas automaticamente
3. Motivo mais frequente (37-40%): ''perda de controle sobre o jogo — saúde mental''', NULL, '5 mi fora das plataformas no total', CAST('["Total de 5 mi fora das plataformas: 1,2 mi voluntários + 3 mi Bolsa Família + 800 mi Desenrola","Plataforma centralizada cobre TODAS as 87 operadoras autorizadas automaticamente","Motivo mais frequente (37-40%): ''perda de controle sobre o jogo — saúde mental''"]' AS JSON), 'Fonte: SPA/MF; Ministro Durigan, ago/2026', 'approved', NULL),
(5, 'B4.12', 48, 'Jogo Responsável: O Que a Regulação Exige', '1. Autolimitação de apostas e depósitos · Alertas regulares sobre tempo e valor
2. SAC obrigatório com atendimento especializado · Material educativo sobre dependência
3. Direito do apostador: encerrar conta + resgatar saldo integral + não ter dados cedidos', NULL, '8 obrigações legais por operador', CAST('["Autolimitação de apostas e depósitos · Alertas regulares sobre tempo e valor","SAC obrigatório com atendimento especializado · Material educativo sobre dependência","Direito do apostador: encerrar conta + resgatar saldo integral + não ter dados cedidos"]' AS JSON), 'Fonte: Portaria SPA/MF 1.231/2024', 'approved', NULL),
(6, 'B5.1', 49, 'Bets no Futebol Brasileiro: A Escala do Fenômeno', '1. 20 das 26 equipes da Série A 2026 têm bets como patrocinadores máster
2. Bets superaram cerveja como principal categoria de patrocinador do futebol brasileiro
3. Naming rights de estádios e cotas de transmissão: próximos campos de disputa', NULL, '20 dos 26 clubes da Série A', CAST('["20 das 26 equipes da Série A 2026 têm bets como patrocinadores máster","Bets superaram cerveja como principal categoria de patrocinador do futebol brasileiro","Naming rights de estádios e cotas de transmissão: próximos campos de disputa"]' AS JSON), 'Fonte: CBF; iGaming Brazil, 2026', 'approved', NULL),
(6, 'B5.2', 50, 'Copa do Mundo 2026: Primeiro Mundial com Mercado Regulado', '1. Copa com sede nos EUA, Canadá e México — jogos em fuso favorável ao apostador brasileiro
2. Operadoras investiram fortemente em marketing pré-Copa — antecipação explica pico de jan
3. Resultado: junho foi o menor GGR do semestre — Copa rearranjou, não expandiu o mercado', NULL, 'Primeiro Mundial com bets legais no Brasil', CAST('["Copa com sede nos EUA, Canadá e México — jogos em fuso favorável ao apostador brasileiro","Operadoras investiram fortemente em marketing pré-Copa — antecipação explica pico de jan","Resultado: junho foi o menor GGR do semestre — Copa rearranjou, não expandiu o mercado"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(6, 'B5.3', 51, 'Publicidade: O Próximo Campo de Batalha Regulatória', '1. Ministro Durigan (29/06): novas restrições via ato administrativo ou MP em preparação
2. Proposta de tratamento similar a álcool e cigarro: advertências obrigatórias nos anúncios
3. CONAR publicou novas diretrizes jan/2026 — influenciadores com 25+ anos para promover apostas', NULL, '230+ PLs sobre publicidade de bets no Congresso', CAST('["Ministro Durigan (29/06): novas restrições via ato administrativo ou MP em preparação","Proposta de tratamento similar a álcool e cigarro: advertências obrigatórias nos anúncios","CONAR publicou novas diretrizes jan/2026 — influenciadores com 25+ anos para promover apostas"]' AS JSON), 'Fonte: BNLData; Poder360; CONAR jan/2026', 'approved', NULL),
(6, 'B5.4', 52, 'CazéTV e a Investigação da Senacon', '1. Senacon abriu procedimento contra CazéTV por possíveis práticas abusivas durante Copa 2026
2. Questão: inserção de apostas e bets durante transmissões ao vivo para audiências amplas
3. Caso emblemático para o debate sobre publicidade contextual e responsabilidade das plataformas', NULL, 'Investigação por inserção em transmissões da Copa', CAST('["Senacon abriu procedimento contra CazéTV por possíveis práticas abusivas durante Copa 2026","Questão: inserção de apostas e bets durante transmissões ao vivo para audiências amplas","Caso emblemático para o debate sobre publicidade contextual e responsabilidade das plataformas"]' AS JSON), 'Fonte: Senacon; BNLData, jun/2026', 'approved', NULL),
(6, 'B5.5', 53, 'O Dilema Regulatório da Publicidade', '1. Tensão estrutural: mais arrecadação → menos incentivo para contrair o mercado
2. Argumento ANJL: restrição publicitária migra apostadores para bets ilegais — caso italiano
3. Argumento contrário: publicidade irrestrita normaliza apostas em populações vulneráveis', NULL, 'Restrição vs. migração para o ilegal', CAST('["Tensão estrutural: mais arrecadação → menos incentivo para contrair o mercado","Argumento ANJL: restrição publicitária migra apostadores para bets ilegais — caso italiano","Argumento contrário: publicidade irrestrita normaliza apostas em populações vulneráveis"]' AS JSON), 'Fonte: BNLData; ANJL; advogado Marcos Poliszezuk, jun/2026', 'approved', NULL),
(6, 'B5.6', 54, 'Inadimplência de Bets com Clubes: Risco Sistêmico', '1. Alfa Bet: cobranças judiciais próximas de R$ 90 mi após suspensão de pagamentos a Grêmio e Inter
2. Ana Gaming encerrou patrocínios com Santos e Vitória por pressão de custos
3. Ausência de garantias financeiras expõe clubes ao risco de crédito das bets', NULL, 'Alfa Bet: ~R$ 90 mi em dívidas com clubes', CAST('["Alfa Bet: cobranças judiciais próximas de R$ 90 mi após suspensão de pagamentos a Grêmio e Inter","Ana Gaming encerrou patrocínios com Santos e Vitória por pressão de custos","Ausência de garantias financeiras expõe clubes ao risco de crédito das bets"]' AS JSON), 'Fonte: BNLData; Folha de S.Paulo, jun/2026', 'approved', NULL),
(6, 'B5.7', 55, 'Influenciadores: Entre o Marketing e o Risco Legal', '1. 412 processos abertos pela SPA · cooperação com CONAR e Conselho Digital do Brasil
2. Nova realidade: influenciadores de bets ilegais respondem por tributos da atividade ilegal
3. Diferenciação regulatória: parceiro de marca autorizada vs. divulgador de operador ilegal', NULL, '324 perfis removidos em 2025-2026', CAST('["412 processos abertos pela SPA · cooperação com CONAR e Conselho Digital do Brasil","Nova realidade: influenciadores de bets ilegais respondem por tributos da atividade ilegal","Diferenciação regulatória: parceiro de marca autorizada vs. divulgador de operador ilegal"]' AS JSON), 'Fonte: SPA/MF jan/2026; Receita Federal jun/2026', 'approved', NULL),
(6, 'B5.8', 56, 'Perspectiva: Publicidade de Bets em 2027', '1. Governo prepara regulamentação específica — forma e extensão ainda indefinidas
2. Cenários: restrição parcial (horários), alerta obrigatório (modelo cigarro) ou restrição ampla
3. Impacto nos modelos de negócio: marketing é a principal barreira de entrada no setor', NULL, 'Definição regulatória esperada até dez/2026', CAST('["Governo prepara regulamentação específica — forma e extensão ainda indefinidas","Cenários: restrição parcial (horários), alerta obrigatório (modelo cigarro) ou restrição ampla","Impacto nos modelos de negócio: marketing é a principal barreira de entrada no setor"]' AS JSON), 'Fonte: BNLData; Durigan, jun/2026', 'approved', NULL),
(7, 'B6.1', 57, '187 Marcas, Mercado Cada Vez Mais Concentrado', '1. Mercado migrou de fragmentado para oligopolista em menos de 18 meses de regulação
2. Piso de sustentabilidade estimado: R$ 5 milhões/mês de faturamento bruto
3. Operadoras abaixo do piso enfrentam custos regulatórios inviáveis — saída ou fusão', NULL, '10 marcas controlam 67% do GGR', CAST('["Mercado migrou de fragmentado para oligopolista em menos de 18 meses de regulação","Piso de sustentabilidade estimado: R$ 5 milhões/mês de faturamento bruto","Operadoras abaixo do piso enfrentam custos regulatórios inviáveis — saída ou fusão"]' AS JSON), 'Fonte: BNLData; Folha de S.Paulo, jun/2026', 'approved', NULL),
(7, 'B6.2', 58, 'Flutter / Betnacional: A Maior Operação', '1. Flutter Entertainment adquiriu 56% da Betnacional por R$ 3,8 bi — aprovado pelo Cade
2. Maior operação registrada no Cade envolvendo bets brasileiras
3. Sinaliza apetite de grupos globais pelo mercado brasileiro como aposta estratégica de longo prazo', NULL, 'R$ 3,8 bi — maior M&A do setor', CAST('["Flutter Entertainment adquiriu 56% da Betnacional por R$ 3,8 bi — aprovado pelo Cade","Maior operação registrada no Cade envolvendo bets brasileiras","Sinaliza apetite de grupos globais pelo mercado brasileiro como aposta estratégica de longo prazo"]' AS JSON), 'Fonte: Cade; BNLData, jun/2026', 'approved', NULL),
(7, 'B6.3', 59, 'RNGX (Bet7K): Consolidação Acelerada', '1. RNGX adquiriu Donald Bet e Bet Ponto Bet no 1S/2026 — aprovações no Cade
2. Market share combinado do grupo: aproximadamente 4,5% do GGR
3. Estratégia: construir escala regional para competir com as grandes globais', NULL, '4,5% de market share combinado', CAST('["RNGX adquiriu Donald Bet e Bet Ponto Bet no 1S/2026 — aprovações no Cade","Market share combinado do grupo: aproximadamente 4,5% do GGR","Estratégia: construir escala regional para competir com as grandes globais"]' AS JSON), 'Fonte: Cade; BNLData, jun/2026', 'approved', NULL),
(7, 'B6.4', 60, 'Alfa Bet: O Risco da Inadimplência Sistêmica', '1. Alfa Bet acumulou cobranças próximas de R$ 90 mi após suspender pagamentos a clubes
2. Empresa busca comprador — caso emblemático do risco de operadoras abaixo do piso
3. Ausência de mecanismo tipo FGC: depósito de R$ 5 mi sem precedente testado na prática', NULL, 'R$ 90 mi em cobranças judiciais', CAST('["Alfa Bet acumulou cobranças próximas de R$ 90 mi após suspender pagamentos a clubes","Empresa busca comprador — caso emblemático do risco de operadoras abaixo do piso","Ausência de mecanismo tipo FGC: depósito de R$ 5 mi sem precedente testado na prática"]' AS JSON), 'Fonte: BNLData; Folha de S.Paulo, jun/2026', 'approved', NULL),
(7, 'B6.5', 61, 'Risco ao Apostador: A Lacuna Regulatória', '1. Regulação exige separação de ativos dos apostadores + depósito de R$ 5 mi por marca
2. Não há mecanismo equivalente ao FGC dos bancos — especialistas apontam lacuna
3. Sem precedente jurídico testado: o que acontece com o saldo se a bet fechar?', NULL, 'Sem FGC equivalente para apostadores', CAST('["Regulação exige separação de ativos dos apostadores + depósito de R$ 5 mi por marca","Não há mecanismo equivalente ao FGC dos bancos — especialistas apontam lacuna","Sem precedente jurídico testado: o que acontece com o saldo se a bet fechar?"]' AS JSON), 'Fonte: BNLData; Folha de S.Paulo; especialistas, jun/2026', 'approved', NULL),
(7, 'B6.6', 62, 'O Mercado em 2027: Quem Vai Sobrar?', '1. Tendência de consolidação acelerada — mercados maduros convergem para 5-8 players dominantes
2. Critérios de sobrevivência: escala, tecnologia, marca forte e capacidade de reter usuários
3. M&A continuará — compradores potenciais: grupos europeus, asiáticos e fundos de PE', NULL, 'Projeção: menos de 50 marcas viáveis', CAST('["Tendência de consolidação acelerada — mercados maduros convergem para 5-8 players dominantes","Critérios de sobrevivência: escala, tecnologia, marca forte e capacidade de reter usuários","M&A continuará — compradores potenciais: grupos europeus, asiáticos e fundos de PE"]' AS JSON), 'Fonte: Análise Stellar Gaming; referências UK, Austrália, 2026', 'approved', NULL),
(7, 'B6.7', 63, 'Competição Por Dentro: O Apostador Multiplataforma', '1. 55,64% usam 2+ plataformas — mas 44,36% são fiéis a uma única operadora
2. Fidelidade é o diferencial estratégico: LTV do apostador fiel supera 3x o do ocasional
3. Apostas ao vivo e cassino online são os segmentos de maior engajamento e retenção', NULL, '44,4% são fiéis a uma única marca', CAST('["55,64% usam 2+ plataformas — mas 44,36% são fiéis a uma única operadora","Fidelidade é o diferencial estratégico: LTV do apostador fiel supera 3x o do ocasional","Apostas ao vivo e cassino online são os segmentos de maior engajamento e retenção"]' AS JSON), 'Fonte: iGaming Brazil / SPA-MF via SIGAP, jul/2026', 'approved', NULL),
(7, 'B6.8', 64, 'Distribuição do GGR: Sportsbook vs. Casino', '1. Sportsbook: vertical original e ainda dominante em volume de apostas
2. Casino online: crescimento mais acelerado, margens maiores e usuário mais frequente
3. Operadoras com presença em ambas as verticais têm vantagem competitiva estrutural', NULL, 'Casino online cresce mais rápido', CAST('["Sportsbook: vertical original e ainda dominante em volume de apostas","Casino online: crescimento mais acelerado, margens maiores e usuário mais frequente","Operadoras com presença em ambas as verticais têm vantagem competitiva estrutural"]' AS JSON), 'Fonte: iGaming Brazil; análise Stellar Gaming, 2026', 'approved', NULL),
(8, 'B7.1', 65, 'Agenda Regulatória: O Que Falta Normatizar', '1. 1. Publicidade: forma e extensão das restrições ainda indefinidas
2. 2. Fornecedores B2B: certificação técnica — norma esperada dez/2026
3. 3. Cassinos físicos: PL em tramitação no Congresso sem prazo definido
4. 4. Monitoramento BCB sobre fintechs: implementação até 1º/dez/2026', NULL, '4 frentes abertas para dez/2026', CAST('["1. Publicidade: forma e extensão das restrições ainda indefinidas","2. Fornecedores B2B: certificação técnica — norma esperada dez/2026","3. Cassinos físicos: PL em tramitação no Congresso sem prazo definido","4. Monitoramento BCB sobre fintechs: implementação até 1º/dez/2026"]' AS JSON), 'Fonte: SPA/MF; BNLData; BCB, jun-ago/2026', 'approved', NULL),
(8, 'B7.2', 66, 'Selic em Queda: O Macro Importa', '1. Boletim Focus projeta Selic encerrando 2026 em ~12,5% — queda de 2,5 p.p. no ano
2. Crédito PF desacelerou: 15,2% (jan/25) → 9,1% (jan/26) no acumulado 12 meses
3. Juro em queda → menos pressão sobre renda comprometida → potencial de expansão do mercado', NULL, 'De 15% para ~12,5% até dez/2026', CAST('["Boletim Focus projeta Selic encerrando 2026 em ~12,5% — queda de 2,5 p.p. no ano","Crédito PF desacelerou: 15,2% (jan/25) → 9,1% (jan/26) no acumulado 12 meses","Juro em queda → menos pressão sobre renda comprometida → potencial de expansão do mercado"]' AS JSON), 'Fonte: Serasa Experian; BCB; Boletim Focus, 2026', 'approved', NULL),
(8, 'B7.3', 67, 'Copa do Mundo 2026: As Lições Para o Mercado', '1. Conclusão: Copa antecipou demanda (pico em jan), não criou demanda nova em junho
2. Operadoras que apostaram só no efeito Copa ficaram abaixo das expectativas
3. Lição: eventos globais são catalisadores de curto prazo — fidelização sustenta o negócio', NULL, 'Copa rearranjou, não expandiu o mercado', CAST('["Conclusão: Copa antecipou demanda (pico em jan), não criou demanda nova em junho","Operadoras que apostaram só no efeito Copa ficaram abaixo das expectativas","Lição: eventos globais são catalisadores de curto prazo — fidelização sustenta o negócio"]' AS JSON), 'Fonte: BNLData / SPA-MF via LAI, ago/2026', 'approved', NULL),
(8, 'B7.4', 68, 'Projeção de Arrecadação 2026-2028', '1. 2026: ~R$ 13-15 bi em tributos federais (+alíquota 13% + crescimento de base)
2. 2027: ~R$ 14-17 bi (alíquota 14% + consolidação do mercado)
3. 2028: R$ 15-18 bi (alíquota 15% + mercado maduro de R$ 55-65 bi de GGR)', NULL, 'R$ 15-18 bi em tributos em 2028', CAST('["2026: ~R$ 13-15 bi em tributos federais (+alíquota 13% + crescimento de base)","2027: ~R$ 14-17 bi (alíquota 14% + consolidação do mercado)","2028: R$ 15-18 bi (alíquota 15% + mercado maduro de R$ 55-65 bi de GGR)"]' AS JSON), 'Fonte: Projeção Stellar Gaming com base em SPA/MF e LC 224/2025', 'approved', NULL),
(8, 'B7.5', 69, 'Cassinos Físicos: O Próximo Capítulo', '1. PL dos cassinos físicos em tramitação no Congresso — sem prazo definido para votação
2. Potencial de adicionar R$ 10-15 bi ao GGR total do mercado se aprovado
3. Operadoras já autorizadas terão preferência no licenciamento — vantagem dos early movers', NULL, 'PL em tramitação — votação em 2027?', CAST('["PL dos cassinos físicos em tramitação no Congresso — sem prazo definido para votação","Potencial de adicionar R$ 10-15 bi ao GGR total do mercado se aprovado","Operadoras já autorizadas terão preferência no licenciamento — vantagem dos early movers"]' AS JSON), 'Fonte: BNLData; MF/SPA; análise Stellar Gaming, 2026', 'approved', NULL),
(8, 'B7.6', 70, 'O Mercado Brasileiro em 2030', '1. Brasil caminha para ser o 4º ou 5º maior mercado regulado do mundo até 2030
2. Projeção: R$ 80-100 bi de GGR anual em 2030 com cassinos físicos incluídos
3. Crescimento demográfico, inclusão financeira e digitalização sustentam expansão estrutural', NULL, 'Top 5 mercados globais até 2030', CAST('["Brasil caminha para ser o 4º ou 5º maior mercado regulado do mundo até 2030","Projeção: R$ 80-100 bi de GGR anual em 2030 com cassinos físicos incluídos","Crescimento demográfico, inclusão financeira e digitalização sustentam expansão estrutural"]' AS JSON), 'Fonte: Grand View Research; Goldman Sachs; análise Stellar Gaming', 'approved', NULL),
(9, 'B8.1', 71, 'UK Gambling Commission: A Referência Global', '1. Reino Unido introduziu verificações de acessibilidade financeira em 2024
2. Resultado: redução de 8% no GGR no primeiro ano — e queda na inadimplência dos apostadores
3. Lição para o Brasil: regulação preventiva funciona — mas exige calibragem para não migrar ao ilegal', NULL, '8% de queda no GGR com affordability checks', CAST('["Reino Unido introduziu verificações de acessibilidade financeira em 2024","Resultado: redução de 8% no GGR no primeiro ano — e queda na inadimplência dos apostadores","Lição para o Brasil: regulação preventiva funciona — mas exige calibragem para não migrar ao ilegal"]' AS JSON), 'Fonte: UK Gambling Commission, abr/2026', 'approved', NULL),
(9, 'B8.2', 72, 'Austrália e Noruega: Dois Modelos Extremos', '1. Austrália: modelo liberal com alto GGR per capita — referência de receita, com críticas sociais
2. Noruega: monopólio estatal (Norsk Tipping) — baixo dano social, baixo GGR privado
3. Brasil: caminho intermediário — mercado privado regulado com obrigações de jogo responsável', NULL, 'Liberal vs. monopólio estatal', CAST('["Austrália: modelo liberal com alto GGR per capita — referência de receita, com críticas sociais","Noruega: monopólio estatal (Norsk Tipping) — baixo dano social, baixo GGR privado","Brasil: caminho intermediário — mercado privado regulado com obrigações de jogo responsável"]' AS JSON), 'Fonte: análise comparativa Stellar Gaming; H2 Gambling Capital, 2026', 'approved', NULL),
(9, 'B8.3', 73, 'Mercado Global: US$ 200 bi até 2030', '1. Mercado global de apostas online estimado em US$ 200 bi até 2030 (Grand View Research)
2. Brasil representa ~60% do mercado latino-americano de apostas online
3. América Latina cresce 3x mais rápido que mercados maduros da Europa e América do Norte', NULL, 'América Latina cresce 3x mais rápido', CAST('["Mercado global de apostas online estimado em US$ 200 bi até 2030 (Grand View Research)","Brasil representa ~60% do mercado latino-americano de apostas online","América Latina cresce 3x mais rápido que mercados maduros da Europa e América do Norte"]' AS JSON), 'Fonte: Grand View Research, fev/2026', 'approved', NULL),
(9, 'B8.4', 74, 'Prediction Markets: Do Polymarket ao Brasil Regulado', '1. Polymarket e Kalshi movimentaram bilhões em previsões políticas e esportivas em 2024-2026
2. Brasil foi um dos primeiros a regular formalmente: Resolução CMN 5.298/2026
3. Equiparação a bets: mesmas obrigações de KYC, tributação e jogo responsável', NULL, 'Brasil: um dos primeiros a regular', CAST('["Polymarket e Kalshi movimentaram bilhões em previsões políticas e esportivas em 2024-2026","Brasil foi um dos primeiros a regular formalmente: Resolução CMN 5.298/2026","Equiparação a bets: mesmas obrigações de KYC, tributação e jogo responsável"]' AS JSON), 'Fonte: SPA/MF abr/2026; BNLData', 'approved', NULL),
(9, 'B8.5', 75, 'Loterias Estaduais: Coexistência ou Competição?', '1. Loterias estaduais operam em paralelo ao mercado federal regulado com regulações diferentes
2. Tensão com Caixa e loterias federais: nichos de público sobrepostos
3. Decisão do STF sobre loterias estaduais pode remodelar o mapa competitivo em 2027', NULL, 'Loto Potiguar e outras iniciativas', CAST('["Loterias estaduais operam em paralelo ao mercado federal regulado com regulações diferentes","Tensão com Caixa e loterias federais: nichos de público sobrepostos","Decisão do STF sobre loterias estaduais pode remodelar o mapa competitivo em 2027"]' AS JSON), 'Fonte: análise Stellar Gaming; BNLData, 2026', 'approved', NULL),
(9, 'B8.6', 76, 'Comparativo de Alíquotas: Onde o Brasil Se Posiciona', '1. UK: 21% sobre GGR · França: 7,5% + 15,6% · Espanha: 20% · Itália: 24%
2. Brasil em 2028 (15%): abaixo de UK e Itália, acima de França e Argentina
3. Progressividade da alíquota dá previsibilidade ao setor — diferencial regulatório positivo', NULL, '13% GGR em 2026 — competitivo globalmente', CAST('["UK: 21% sobre GGR · França: 7,5% + 15,6% · Espanha: 20% · Itália: 24%","Brasil em 2028 (15%): abaixo de UK e Itália, acima de França e Argentina","Progressividade da alíquota dá previsibilidade ao setor — diferencial regulatório positivo"]' AS JSON), 'Fonte: H2 Gambling Capital; análise Stellar Gaming, 2026', 'approved', NULL),
(9, 'B8.7', 77, 'Apostas ao Vivo: O Maior Catalisador de Crescimento', '1. Apostas ao vivo (in-play) respondem por 70-80% do GGR em mercados maduros como UK
2. No Brasil ainda em crescimento acelerado — tecnologia de odds em tempo real é vantagem B2B
3. Transmissões ao vivo integradas com plataformas de apostas: tendência global irreversível', NULL, 'In-play: 70-80% do GGR em mercados maduros', CAST('["Apostas ao vivo (in-play) respondem por 70-80% do GGR em mercados maduros como UK","No Brasil ainda em crescimento acelerado — tecnologia de odds em tempo real é vantagem B2B","Transmissões ao vivo integradas com plataformas de apostas: tendência global irreversível"]' AS JSON), 'Fonte: H2 Gambling Capital; iGaming Brazil; análise Stellar Gaming, 2026', 'approved', NULL),
(10, 'B9.1', 78, 'Stellar Gaming: Dois Produtos, Uma Visão', '1. Estrelabet: sportsbook e cassino online com posicionamento premium no mercado brasileiro
2. Vupi: vertical complementar com proposta diferenciada de produto e público
3. Stellar Group opera ambas as marcas no mercado regulado desde o início (jan/2025)', NULL, 'Estrelabet + Vupi · Born to Lead', CAST('["Estrelabet: sportsbook e cassino online com posicionamento premium no mercado brasileiro","Vupi: vertical complementar com proposta diferenciada de produto e público","Stellar Group opera ambas as marcas no mercado regulado desde o início (jan/2025)"]' AS JSON), 'Fonte: Stellar Gaming, 2026', 'approved', NULL),
(10, 'B9.2', 79, 'Nossa Posição no Mercado Regulado', '1. Participação no GGR do mercado regulado: ~1,3% a ~2,3% no período jan-abr/2026
2. Pico de participação em mar/2026 (~2,27%) — consistência como métrica de qualidade operacional
3. Estratégia: crescimento sustentável com foco em retenção e valor por usuário (LTV)', NULL, 'Market share em crescimento no 1S/2026', CAST('["Participação no GGR do mercado regulado: ~1,3% a ~2,3% no período jan-abr/2026","Pico de participação em mar/2026 (~2,27%) — consistência como métrica de qualidade operacional","Estratégia: crescimento sustentável com foco em retenção e valor por usuário (LTV)"]' AS JSON), 'Fonte: Stellar Gaming — análise interna, mai/2026', 'approved', NULL),
(10, 'B9.3', 80, 'Metodologia Deste Relatório', '1. Fontes primárias preferidas: SPA/MF via LAI, Receita Federal, Serasa Experian, SIGAP
2. Classificação: ATUAL (2026) = base principal · REF (pré-2026) = uso comparativo
3. Produzido com suporte de IA (Claude, Anthropic) — curadoria e revisão: Fellipe Fraga, Stellar Gaming', NULL, 'Transparência metodológica não é opcional', CAST('["Fontes primárias preferidas: SPA/MF via LAI, Receita Federal, Serasa Experian, SIGAP","Classificação: ATUAL (2026) = base principal · REF (pré-2026) = uso comparativo","Produzido com suporte de IA (Claude, Anthropic) — curadoria e revisão: Fellipe Fraga, Stellar Gaming"]' AS JSON), 'Stellar Gaming · Relatório Setorial 2026', 'approved', NULL),
(10, 'B9.4', 81, 'Born to Lead', '1. O Brasil está no centro do maior processo de regulação de apostas do mundo em escala
2. As empresas que construírem fundamentos sólidos hoje definirão o mercado de amanhã
3. Stellar Gaming está aqui desde o primeiro dia — e estará nos próximos capítulos dessa história', NULL, 'O mercado está sendo construído agora', CAST('["O Brasil está no centro do maior processo de regulação de apostas do mundo em escala","As empresas que construírem fundamentos sólidos hoje definirão o mercado de amanhã","Stellar Gaming está aqui desde o primeiro dia — e estará nos próximos capítulos dessa história"]' AS JSON), 'Stellar Gaming · Born to Lead · 2026', 'approved', NULL);

INSERT INTO appConfig (`key`, `value`) VALUES
  ('claude_model', 'claude-sonnet-4-6'),
  ('claude_temperature', '0.2'),
  ('claude_base_prompt', 'Você é o processador de inteligência editorial do Relatório Stellar Gaming 2026. Produza conteúdo técnico, rigoroso, em português, baseado exclusivamente nas fontes fornecidas. Não invente dados; sinalize lacunas como a confirmar. Sugira alocação apenas entre os 81 slides do sumário editorial.'),
  ('anthropic_key', ''),
  ('current_sumario', 'Relatório Setorial Stellar Gaming 2026 — 81 slides organizados em 10 seções.')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

SELECT COUNT(*) AS seeded_slide_count FROM slides;
